<?php
session_start();
$paypal_url='https://www.sandbox.paypal.com/cgi-bin/webscr';
$paypal_id='linyusos@gmail.com';  // sriniv_1293527277_biz@inbox.com
?>
<form action='<?php echo $paypal_url; ?>' method='post' name='frmPayPal1'>
    <div class="cart">
        <table class="table">
            <thead>
            <tr>
                <th>QTY</th>
                <th>Name</th>
                <th>Price</th>
                <th>sub total</th>
            </tr>
            </thead>
            <tbody>
            <input type="hidden" name="cmd" value="_cart">
            <input type="hidden" name="upload" value="1">
            <input type='hidden' name='business' value='<?php echo $paypal_id;?>'>
            <?php foreach($carts  as $key => $cart): ?>
                <?php $itemkey = $key+1 ; ?>
                <tr class="active">
                    <td>
                        <input type='text' name='quantity_<?php echo $itemkey; ?>' value='<?php echo $cart[qty] ?>'>
                    </td>
                    <td><input type='text' name='item_name_<?php echo $itemkey; ?>' value='<?php echo  $cart[fname]?>'></td>
                    <td><input type='text' name='amount_<?php echo $itemkey; ?>' value='<?php echo  $cart[price]?>'></td>
                    <td><?php $oneDishTotal = $cart[price]*$cart[qty]; echo $oneDishTotal; ?></td>
                    <td><a href="remove?id=<?php echo $cart[id] ?>&sid=<?php echo $sid ?>">remove item</a></td>
                </tr>
                <?php $total +=$oneDishTotal; ?>
            <?php endforeach; ?>
            </tbody>
        </table>
        <div class="total">total: <input type='text' name='amount' value='<?php echo $total ?>'>€</div>
        <div class="clearcart"><a href="removeall?sid=<?php echo $sid ?>">clear shopping cart</a></div>
        <?php if(strpos($this->serverUrl(true),'cn') == false) : ?>
        <div class="continue"><a href="<?php echo $this->serverUrl() ?>/en/menu">continue shopping</a></div>
        <?php else : ?>
        <div class="continue"><a href="<?php echo $this->serverUrl() ?>/cn/menu">continue shopping</a></div>
        <?php endif; ?>
        <input type="image" src="https://www.sandbox.paypal.com/en_US/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
        <img alt="" border="0" src="https://www.sandbox.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1">
    </div>
</form>