<div class="dynamic-content restaurant-wrapper" id="main-content">
    <div class="container">
        <div id="buffetAdmin" class="padding-wrapper">

<?php
$title = "Delete a buffet dish";
$this->headTitle($title);
?>

<h2><?php echo $this->escapeHtml($title); ?></h2>

<form
    action="<?= $this->url('buffetAdmin', array('action' => 'delete', 'weekMark' => $this->weekMark, 'id' => $this->id)) ?>"
    method="post">
    <p>
        Are you sure you want to delete this buffet dish?<br/>
        <?= $this->buffet->cName ?><br/>
        <?= $this->buffet->fName ?>
    </p>

    <!-- submit button -->
    <div>
        <button type="submit" name="delete_btn" value="Yes">Yes</button>
        <button type="submit" name="delete_btn" value="No">No</button>
    </div>

</form>
        </div>
    </div>
</div>