<?php
$title = 'Buffet Menu';
$this->headTitle($title);
?>

<h2><?php echo $this->escapeHtml($title); ?></h2>


<!--buffet menu 1-->
<!--    link: listview-->
<hr>
<div>
    <p>
        <a href="<?= $this->url('buffetAdmin', array('action' => 'listView', 'weekMark' => '1')) ?>"> <i
                class="icon-pencil"></i> Buffet 单周 </a>
    </p>
</div>


<!--buffet menu 2-->
<!--    link: listview-->
<hr>
<div>
    <p>
        <a href="<?= $this->url('buffetAdmin', array('action' => 'listView', 'weekMark' => '2')) ?>"> <i
                class="icon-pencil"></i> Buffet 双周 </a>
    </p>
</div>