<?php
$title = 'Buffet Menu';
$this->headTitle($title);
?>

<h2><?php echo $this->escapeHtml($title); ?></h2>

<hr>
<div>
    <p>
        <a href="<?= $this->url('buffetAdmin', array('action' => 'add', 'weekMark' => $this->weekMark)) ?>"> <i
                class="icon-pencil"></i> Add a dish
        </a>
    </p>
</div>

<table class="table">

    <tr>
        <th>dayMark</th>
        <th>display_order</th>
        <th>cName</th>
        <th>eName</th>
        <th>fName</th>
        <th>spice</th>
        <th>cold_dish</th>
        <th>edit</th>
    </tr>

    <?php foreach ($this->buffet as $buffet_dish) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($buffet_dish->getDayMark()); ?></td>
            <td><?php echo $this->escapeHtml($buffet_dish->displayOrder); ?></td>
            <td><?php echo $this->escapeHtml($buffet_dish->cName); ?></td>
            <td><?php echo $this->escapeHtml($buffet_dish->eName); ?></td>
            <td><?php echo $this->escapeHtml($buffet_dish->fName); ?></td>
            <td><?php echo $this->escapeHtml($buffet_dish->spiceDegree); ?></td>
            <td><?php echo $this->escapeHtml($buffet_dish->coldDish); ?></td>

            <?php if ($this->weekMark == '1'): ?>
                <td>
                    <a href="<?= $this->url('buffetAdmin', array('action' => 'edit', 'id' => $buffet_dish->buffet1Id, 'weekMark' => $this->weekMark)) ?>">
                        edit </a>
                </td>
                <td>
                    <a href="<?= $this->url('buffetAdmin', array('action' => 'delete', 'id' => $buffet_dish->buffet1Id, 'weekMark' => $this->weekMark)) ?>">
                        delete</a>
                </td>
            <?php elseif ($this->weekMark == '2') : ?>
                <td>
                    <a href="<?= $this->url('buffetAdmin', array('action' => 'edit', 'id' => $buffet_dish->buffet2Id, 'weekMark' => $this->weekMark)) ?>">
                        edit </a>
                </td>
                <td>
                    <a href="<?= $this->url('buffetAdmin', array('action' => 'delete', 'id' => $buffet_dish->buffet2Id, 'weekMark' => $this->weekMark)) ?>">
                        delete</a>
                </td>
            <?php endif; ?>

        </tr>
    <?php endforeach; ?>

</table>