<?php
$title = 'Reservation';
$this->headTitle($title);
?>

<h2><?php echo $this->escapeHtml($title); ?></h2>
<hr/>

<?php
$form = $this->ReservationSearchForm;
$form->prepare();
$form->setAttribute('action', $this->url('reservation', array('action' => 'index')));
$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);

echo $this->formElement($form->get('date')) . "<br>";
echo $this->formElement($form->get('time_h')) . "<br>";
echo $this->formElement($form->get('time_m')) . "<br>";
echo $this->formElement($form->get('submit')) . "<br>";

echo $this->form()->closeTag();

?>