<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headMeta()
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0')

        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/less/jquery.maximage.css')
                        ->prependStylesheet('http://fonts.googleapis.com/css?family=Covered+By+Your+Grace')
                        ->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:400,300,600&amp;subset=latin,latin-ext') // added
                        ->prependStylesheet($this->basePath() . '/less/custom.css')
                        ->prependStylesheet($this->basePath() . '/css/fusion.css')?>



        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/modernizr-2.6.2.min.js') // added
            ->prependFile($this->basePath() . '/js/jquery-2.0.3.min.js')
        ?>

    </head>
    <body>


        <!--[if lt IE 7]>
        <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <div class="top languages layout-languages">
            <?php
            $this->serverUrl() ;
            $route = str_replace($this->serverUrl() ,'',$this->serverUrl(true));
            $route = str_replace('/en' ,'',$route);
            $route = str_replace('/cn' ,'',$route);

            if ($route=="/"||$route=="/index"){
                $homeUrl = str_replace('index' ,'',$this->serverUrl());
                $enUrl = $homeUrl.'en';
                $cnUrl = $homeUrl.'cn';
            }else{
                $enUrl = $this->serverUrl().'/en'.$route;
                $cnUrl = $this->serverUrl().'/cn'.$route;
            }
            ?>
            <ul>
                <li>
                    <a  href="<?php echo $enUrl; ?>"  title="Finnish"><span>FI</span></a>
                </li>
                <li>
                    <a  href="<?php echo $cnUrl; ?>"  title="Chinese"><span>CN</span></a>
                </li>
            </ul>
        </div>
        <!-- Add your site or application content here -->
        <div class="container full-bg visible-xs sm-navbar">
            <nav>
                <div class="row">
                    <div class="navbar-inner">
                        <ul class="main-menu nav">
                            <li>
                                <header class="small-logo">
                                    <a href="<?php echo $this->serverUrl(); ?>" title=""><img src="<?php echo $this->serverUrl();?>/img/logo.png" alt="Barnelli"/></a>
                                </header>
                            </li>
                            <li class="reorder">
                                <a href="#" title="" class="exclude" data-djax-exclude="true"><i class="fa fa-reorder"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <div id="mobile-nav" class="visible-xs">
            <div class="" id="flyout-container">
                <ul id="menu-mobile" class="nav flyout-menu">
                    <li class="menu-item">
                        <a title="" href="restaurant">Restaurant</a>
                    </li>
                    <li class="menu-item">
                        <a title="" href="menu">Menu</a>
                    </li>
                    <li class="menu-item">
                        <a title="" href="reservation">Reservation</a>
                    </li>
                    <li class="menu-item">
                        <a title="" href="contact">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="navbar hidden-xs">
            <div class="container">
                <div class="row">
                    <nav class="col-md-12 clearfix">
                        <ul class="main-nav white-nav dotted-separator">
                            <li>
                                <div>
                                    <a href="restaurant" class="content-link restaurant-wrapper"><span><?php echo $this->translate('Restaurant') ?></span> <img src="<?php echo $this->serverUrl();?>/img/icon-restaurant.png" width="32" height="32" alt=""/></a>
                                </div>
                            </li>
                            <li>
                                <div>
                                    <?php  $baseurlwithlanguage = str_replace($route ,'',$this->serverUrl(true)); ?>
                                    <?php if ((strpos($baseurlwithlanguage,'cn')!== false) || (strpos($baseurlwithlanguage,'en')!== false)) :?>
                                    <a href="<?php echo $baseurlwithlanguage ?>/menu" class="content-link menu-wrapper"><span><?php echo $this->translate('Menu') ?></span> <img src="<?php echo $this->serverUrl();?>/img/icon-menu.png" alt="" /></a>
                                    <?php else : ?>
                                        <a href="<?php echo $this->serverUrl() ?>/en/menu" class="content-link menu-wrapper"><span><?php echo $this->translate('Menu') ?></span> <img src="<?php echo $this->serverUrl();?>/img/icon-menu.png" alt="" /></a>
                                    <?php endif; ?>
                                </div>
                            </li>
                            <li>
                                <div>
                                    <a href="gallery" class="content-link gallery-wrapper"><span><?php echo $this->translate('Gallery') ?></span> <img src="<?php echo $this->serverUrl();?>/img/icon-gallery.png" width="32" height="32" alt=""/></a>
                                </div>
                            </li>
                            <li class="menu-image">
                                <div>
                                    <a class="content-link logo" title="logo" href="<?php echo $this->serverUrl(); ?>"><img src="<?php echo $this->serverUrl();?>/img/WEBLOGO.png"  ></a>
                                </div>
                            </li>
                            <li>
                                <div>
                                    <?php  $baseurlwithlanguage = str_replace($route ,'',$this->serverUrl(true)); ?>
                                    <?php if ((strpos($baseurlwithlanguage,'cn')!== false) || (strpos($baseurlwithlanguage,'en')!== false)) :?>
                                        <a href="<?php echo $baseurlwithlanguage ?>/buffet" class="content-link buffet-wrapper"><span><?php echo $this->translate('buffet') ?></span> <img src="<?php echo $this->serverUrl();?>/img/icon-buffet.png" alt="" /></a>
                                    <?php else : ?>
                                        <a href="<?php echo $this->serverUrl() ?>/en/buffet" class="content-link buffet-wrapper"><span><?php echo $this->translate('buffet') ?></span> <img src="<?php echo $this->serverUrl();?>/img/icon-buffet.png" alt="" /></a>
                                    <?php endif; ?>
                                </div>
                            </li>
                            <li>
                                <div>
                                    <a href="reservation" class="content-link reservation-wrapper"><span><?php echo $this->translate('Reservation') ?></span> <img src="<?php echo $this->serverUrl();?>/img/icon-reservation.png" alt=""/></a>
                                </div>
                            </li>
                            <li>
                                <div>
                                    <a href="contact" class="content-link contact-wrapper"><span><?php echo $this->translate('Contact') ?></span><img src="<?php echo $this->serverUrl();?>/img/icon-contact.png" alt=""/></a>
                                </div>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>

        <div id="content-wrapper">
                <?php echo $this->content; ?>
        </div><!-- /container -->

    </body>
    <!-- Scripts -->
    <?php echo $this->inlineScript()
        ->appendFile($this->basePath() . '/js/jquery.djax.js')
        ->appendFile($this->basePath() . '/js/jquery.nicescroll.min.js')
        ->appendFile($this->basePath() . '/js/jquery.ba-throttle-debounce.min.js')
        ->appendFile($this->basePath() . '/js/transit.js')
        ->appendFile($this->basePath() . '/js/jquery.cycle.all.min.js')
        ->appendFile($this->basePath() . '/js/jquery.maximage.min.js')
        ->appendFile($this->basePath() . '/js/jquery.colorbox-min.js')
        ->appendFile($this->basePath() . '/js/owl.carousel.min.js')
        ->appendFile($this->basePath() . '/js/main.js');
    ?>
</html>


