<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0')

        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/less/jquery.maximage.css')
                        ->prependStylesheet('http://fonts.googleapis.com/css?family=Covered+By+Your+Grace')
                        ->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:400,300,600&amp;subset=latin,latin-ext') // added
                        ->prependStylesheet($this->basePath() . '/less/custom.css')?>



        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/modernizr-2.6.2.min.js') // added
            ->prependFile($this->basePath() . '/js/jquery-2.0.3.min.js')
        ?>

    </head>
    <body>


        <!--[if lt IE 7]>
        <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <!-- Add your site or application content here -->
        <div class="container full-bg visible-xs sm-navbar">
            <nav>
                <div class="row">
                    <div class="navbar-inner">
                        <ul class="main-menu nav">
                            <li>
                                <header class="small-logo">
                                    <a href="" title=""><img src="img/logo.png" alt="Barnelli"/></a>
                                </header>
                            </li>
                            <li class="reorder">
                                <a href="#" title="" class="exclude" data-djax-exclude="true"><i class="fa fa-reorder"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <div id="mobile-nav" class="visible-xs">
            <div class="" id="flyout-container">
                <ul id="menu-mobile" class="nav flyout-menu">
                    <li class="menu-item-has-children menu-item">
                        <a title="" href="">Restaurant</a>
                        <span class="open-children"><i class="fa fa-angle-down"></i></span>
                        <ul class="subnav">
                            <li><a href="" title=""><span>Blog</span></a></li>
                            <li><a href="" title=""><span>Team</span></a></li>
                        </ul>
                    </li>
                    <li class="menu-item-has-children menu-item">
                        <a title="" href="">Menu</a>
                        <span class="open-children"><i class="fa fa-angle-down"></i></span>
                        <ul class="subnav">
                            <li><a href="" title=""><span>Menu 1</span></a></li>
                            <li><a href="" title=""><span>Menu 2</span></a></li>
                            <li><a href="" title=""><span>Menu 3</span></a></li>
                        </ul>
                    </li>
                    <li class="menu-item">
                        <a title="" href="">Reservation</a>
                    </li>
                    <li class="menu-item">
                        <a title="" href="">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="navbar hidden-xs">
            <div class="container">
                <div class="row">
                    <nav class="col-md-12 clearfix">
                        <ul class="main-nav white-nav dotted-separator">
                            <li>
                                <div>
                                    <a href="" class="content-link restaurant-wrapper"><span>Restaurant</span> <img src="img/icon1.png" alt=""/></a>
                                </div>
                            </li>
                            <li>
                                <div>
                                    <a href="menu" class="content-link menu-wrapper menu-item-has-children"><span>Menu</span> <img src="img/icon2.png" alt=""/></a>
                                </div>
                            </li>
                            <li>
                                <div>
                                    <a href="menu" class="content-link menu-wrapper menu-item-has-children"><span>Gallery</span> <img src="img/icon2.png" alt=""/></a>
                                </div>
                            </li>
                            <li class="menu-image">
                                <div>
                                    <a class="content-link" title="logo" href=""><img src="img/logo.png" alt=""></a>
                                </div>
                            </li>
                            <li>
                                <div>
                                    <a href="buffet" class="content-link menu-wrapper menu-item-has-children"><span>Buffet</span> <img src="img/icon2.png" alt=""/></a>
                                </div>
                            </li>
                            <li>
                                <div>
                                    <a href="" class="content-link reservation-wrapper"><span>Reservation</span> <img src="img/icon3.png" alt=""/></a>
                                </div>
                            </li>
                            <li>
                                <div>
                                    <a href="" class="content-link contact-wrapper"><span>Contact </span><img src="img/icon4.png" alt=""/></a>
                                </div>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>

        <div id="content-wrapper">
            <div class="dynamic-content container" id="main-content">
                <?php echo $this->content; ?>
            </div>
        </div><!-- /container -->

    </body>
    <!-- Scripts -->
    <?php echo $this->inlineScript()
        ->appendFile($this->basePath() . '/js/jquery.djax.min.js')
        ->appendFile($this->basePath() . '/js/jquery.nicescroll.min.js')
        ->appendFile($this->basePath() . '/js/jquery.ba-throttle-debounce.min.js')
        ->appendFile($this->basePath() . '/js/transit.js')
        ->appendFile($this->basePath() . '/js/jquery.cycle.all.min.js')
        ->appendFile($this->basePath() . '/js/jquery.maximage.min.js')
        ->appendFile($this->basePath() . '/js/jquery.colorbox-min.js')
        ->appendFile($this->basePath() . '/js/owl.carousel.min.js')
        ->appendFile($this->basePath() . '/js/main.js');
    ?>
</html>


