<?php
$title = 'Buffet Menu';
$this->headTitle($title);
?>


<!-- Buffet Menu for the week -->

<h2><?php echo $this->escapeHtml($title . ' for the week'); ?></h2>

<table class="table">

    <tr>
        <th>dayMark</th>
        <th>display_order</th>
        <th>cName</th>
        <th>eName</th>
        <th>fName</th>
        <th>spice</th>
        <th>cold_dish</th>
    </tr>

    <?php foreach ($this->buffet as $buffet_dish) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($buffet_dish->dayMark); ?></td>
            <td><?php echo $this->escapeHtml($buffet_dish->displayOrder); ?></td>
            <td><?php echo $this->escapeHtml($buffet_dish->cName); ?></td>
            <td><?php echo $this->escapeHtml($buffet_dish->eName); ?></td>
            <td><?php echo $this->escapeHtml($buffet_dish->fName); ?></td>
            <td><?php echo $this->escapeHtml($buffet_dish->spiceDegree); ?></td>
            <td><?php echo $this->escapeHtml($buffet_dish->coldDish); ?></td>
        </tr>
    <?php endforeach; ?>

</table>


<!-- Buffet Menu for today -->

<h2><?php echo $this->escapeHtml($title . ' for today'); ?></h2>

<table class="table">

    <tr>
        <th>dayMark</th>
        <th>display_order</th>
        <th>cName</th>
        <th>eName</th>
        <th>fName</th>
        <th>spice</th>
        <th>cold_dish</th>
    </tr>

    <?php foreach ($this->buffet as $buffet_dish) : ?>
        <?php if ($buffet_dish->dayMark == $this->dayMark): ?>
            <tr>
                <td><?php echo $this->escapeHtml($buffet_dish->dayMark); ?></td>
                <td><?php echo $this->escapeHtml($buffet_dish->displayOrder); ?></td>
                <td><?php echo $this->escapeHtml($buffet_dish->cName); ?></td>
                <td><?php echo $this->escapeHtml($buffet_dish->eName); ?></td>
                <td><?php echo $this->escapeHtml($buffet_dish->fName); ?></td>
                <td><?php echo $this->escapeHtml($buffet_dish->spiceDegree); ?></td>
                <td><?php echo $this->escapeHtml($buffet_dish->coldDish); ?></td>
            </tr>
        <?php endif; ?>
    <?php endforeach; ?>

</table>