<div class="dynamic-content buffet-wrapper" id="main-content">
    <div id="second-menu" class="menu padding-wrapper">
        <div id="buffet" class="container animate-in animate-in-fade">
            <?php
            $title = 'Buffet Menu';
            $this->headTitle($title);
            ?>

            <header class="row">
                <div class="col-md-12">
                    <ul id="tabs">
                        <li><a href="#" name="tab1" class="Monday"><?php echo $this->translate('Monday') ?></a></li>
                        <li><a href="#" name="tab2" class="Tuesday"><?php echo $this->translate('Tuesday') ?></a></li>
                        <li><a href="#" name="tab3" class="Wednesday"><?php echo $this->translate('Wednesday') ?></a></li>
                        <li><a href="#" name="tab4" class="Thursday"><?php echo $this->translate('Tuesday') ?></a></li>
                        <li><a href="#" name="tab5" class="Friday"><?php echo $this->translate('Friday') ?></a></li>
                    </ul>
                </div>
            </header>

            <div id="tab-content">
                <?php for ($count = 1; $count <= 5; $count++): ?>
                    <div id="tab<?= $count ?>">
                        <header class="row">
                            <div class="col-md-12">
                                <div class="menu-header">
                                    <h2><span>Main Course <i class="fa fa-bookmark"></i></span></h2>
                                </div>
                            </div>
                        </header>
                        <section class="row">
                            <div class="col-md-12">

                                <dl>
                                    <article>
                                        <?php foreach ($this->buffet as $buffet_dish) : ?>
                                            <?php if ($buffet_dish->dayMark == $count && $buffet_dish->coldDish != 1): ?>
                                                <dd class="menu-list">
                                                    <section class="menu-item">
                                                        <p class="title"><?php echo $this->escapeHtml($buffet_dish->fName); ?>
                                                            <span><?php echo $this->escapeHtml($buffet_dish->cName); ?></span>
                                                        </p>
                                                    </section>
                                                </dd>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                    </article>
                                </dl>
                            </div>
                        </section>
                        <header class="row">
                            <div class="col-md-12">
                                <div class="menu-header">
                                    <h2><span>Kiinalaisia kylmä tarjoiitavat 特色凉菜 <i class="fa fa-bookmark"></i></span>
                                    </h2>
                                </div>
                            </div>
                        </header>
                        <section class="row">
                            <div class="col-md-12">
                                <dl>
                                    <article>
                                        <?php foreach ($this->buffet as $buffet_dish) : ?>
                                            <?php if ($buffet_dish->dayMark == $count && $buffet_dish->coldDish == 1): ?>
                                                <dd class="menu-list">
                                                    <section class="menu-item">
                                                        <p class="title"><?php echo $this->escapeHtml($buffet_dish->fName); ?>
                                                            <span><?php echo $this->escapeHtml($buffet_dish->cName); ?></span>
                                                        </p>
                                                    </section>
                                                </dd>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                    </article>
                                </dl>
                            </div>
                        </section>
                        <header class="row">
                            <div class="col-md-12">
                                <div class="menu-header">
                                    <h2><span>Jälkiruoka 甜点 <i class="fa fa-bookmark"></i></span></h2>
                                </div>
                            </div>
                        </header>
                        <section class="row">
                            <div class="col-md-12">
                                <dl>
                                    <article>
                                        <?php foreach ($this->buffet as $buffet_dish) : ?>
                                            <?php if ($buffet_dish->dayMark == $count && $buffet_dish->coldDish == 2): ?>
                                                <dd class="menu-list">
                                                    <section class="menu-item">
                                                        <p class="title"><?php echo $this->escapeHtml($buffet_dish->fName); ?>
                                                            <span><?php echo $this->escapeHtml($buffet_dish->cName); ?></span>
                                                        </p>
                                                    </section>
                                                </dd>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                    </article>
                                </dl>
                            </div>
                        </section>
                    </div>

                <?php endfor; ?>
            </div>


        </div>
    </div>
</div>


<script type="text/javascript">
    // buffet tabs
    $(document).ready(function () {
        $("#tab-content").find("[id^='tab']").hide(); // Hide all content
//        $("#tabs li:first").attr("id", "current"); // Activate the first tab
        $("li:nth-child(<?=$this->dayMark?>)").attr("id", "current"); // Activate the first tab

        $("#tab-content #tab1").fadeIn(); // Show first tab's content

        $('#tabs a').click(function (e) {
            e.preventDefault();
            if ($(this).closest("li").attr("id") == "current") { //detection for current tab
                return;
            }
            else {
                $("#tab-content").find("[id^='tab']").hide(); // Hide all content
                $("#tabs li").attr("id", ""); //Reset id's
                $(this).parent().attr("id", "current"); // Activate this
                $('#' + $(this).attr('name')).fadeIn(); // Show content for the current tab
            }
        });
    });
</script>




