<?php
$title = "Edit a buffet dish";
$this->headTitle($title);
?>

<h2><?php echo $this->escapeHtml($title); ?></h2>

<?php
$form = $this->form;
//$form = new \Zend\Form\Form();
$form->prepare();
$form->setAttribute('action', $this->url('buffet1', array('action' => 'edit', 'id' => $this->id)));
$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);

echo $this->formRow($form->get('dayMark')) . "<br>";
echo $this->formRow($form->get('displayOrder')) . "<br>";
echo $this->formRow($form->get('cName')) . "<br>";
echo $this->formRow($form->get('eName')) . "<br>";
echo $this->formRow($form->get('fName')) . "<br>";
echo $this->formRow($form->get('spiceDegree')) . "<br>";
echo $this->formRow($form->get('coldDish')) . "<br>";
echo $this->formSubmit($form->get('submit')) . "<br>";


echo $this->form()->closeTag();



?>

