<?php
$title = 'Dish table';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<table style="width:100%">


<?php foreach($categories as $category) : ?>
    <div class="category">
    <h1><?php echo $category->getName() ; ?></h1>
    <?php foreach ($dishes as $dish) : ?>
        <form action="cart/add" method="get">
            <?php if( $dish->category->getName() == $category->getName() ): ?>
            <div class="dish">
            <?php echo $this->escapeHtml($dish->fName); ?>
            <?php echo $this->escapeHtml($dish->cName); ?>
            <?php echo $this->escapeHtml($dish->eName); ?>
            <?php echo $this->escapeHtml($dish->description); ?>
            <?php echo $this->escapeHtml($dish->spiceDgree); ?>
            <img src="/uploads/<?php echo $this->escapeHtml($dish->image); ?>" alt="Smiley face" height="42" width="42">
            <?php echo $this->escapeHtml($dish->restaurant->getName()); ?>
            <select name="qty">
                <option value="1" selected="selected">Please select amount</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
            </select>
            <input type="hidden" name="id" value="<?php echo $this->escapeHtml($dish->dishId); ?>" />
            </div>
            <input type="submit" value="add to cart" class="btn btn-primary">
        <?php endif; ?>
        </form>
    <?php endforeach; ?>
    </div>
<?php endforeach; ?>   
    

</table>
