<div class="dynamic-content contact-wrapper" id="main-content">
    <section id="contact" class="padding-wrapper">
        <div class="container">
            <div id="map" class="map"></div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-4">
                    <div class="row">
                        <div class="col-sm-6 col-md-12">
                            <div class="info">
                                <h1>Info</h1>
                                <p>Lorem ipsum nunc gravida ut ornare, id at varius quam. Mattis quis tortor hendrerit, mollis ligula platea rhoncus, himenaeos facilisis. Condimentum et urna sit blandit ultricies, nullam arcu eget proin. </p>
                            </div>
                        </div>
                        <div class="col-sm-offset-1 col-sm-5 col-md-12 col-md-offset-0">
                            <div class="social-media">
                                <h1>Find us on</h1>
                                <ul class="social-icon">
                                    <li>
                                        <a href="https://facebook.com"><i class="fa fa-facebook"></i></a>
                                    </li>
                                    <li>
                                        <a href="https://google.com"><i class="fa fa-google-plus"></i></a>
                                    </li>
                                    <li>
                                        <a href="https://twitter.com"><i class="fa fa-twitter"></i></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class=" col-sm-6 col-md-4 col-md-offset-1">
                    <div class="vcard">
                        <h1>Adress &amp; Phone</h1>
                        <p class="adr">
                            <span class="company-name">Barnelli Cafe &amp; Restaurnt</span>
                            <span class="street-address">Zdrowa 18</span>
                            <span class="postal-code">53-511 Wrocław</span>
                        </p>
                        <p>
                            <span class="email">email: <a class="email" href="mailto:lavenda@cafe.com" title="">lavenda@cafe.com</a></span>
                            <span class="tel">mobile: <span>+48 122 33 66</span></span>
                        </p>
                    </div>
                </div>
                <div class="col-sm-offset-1 col-sm-5 col-md-3 col-md-offset-0 form">
                    <form id="contact-form" name="contact-form" action="?" method="post">
                        <h1>Contact Form</h1>
                        <div class="input-wrapper">
                            <input class="contact-form" type="text" placeholder="name" name="form-name" id="form-name">
                        </div>
                        <div class="input-wrapper">
                            <input class="contact-form" type="text" placeholder="e-mail" name="form-email" id="form-email">
                        </div>
                        <div class="input-wrapper">
                            <input class="contact-form" type="text" placeholder="subject" name="form-subject" id="form-subject">
                        </div>
                        <div class="message">
                            <div class="input-wrapper">
                                <textarea class="contact-form" placeholder="message" name="form-message" id="form-message"></textarea>
                            </div>
                        </div>
                        <div class="message">
                            <div class="input-wrapper">
                                <div class="captcha-container">
                                    <div>
                                        <input class="contact-form" type="text" placeholder="captcha" name="form-captcha" id="form-captcha">
                                        <img id="captcha" src="inc/securimage/securimage_show.php" alt="captcha">
                                        <button class="refresh-captcha"><i class="fa fa-refresh"></i></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="alert alert-success hidden">Your message was sent. Thank you!</div>
                        <div>
                            <input type="submit" value="Send" class="buttonform">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
</div>
