<div class="dynamic-content container" id="main-content">
    <div class="social-share top">
        <ul>
            <li>
                <a href="https://facebook.com"><i class="fa fa-facebook"></i></a>
            </li>
            <li>
                <a href="https://twitter.com"><i class="fa fa-twitter"></i></a>
            </li>
            <li>
                <a href="https://google.com"><i class="fa fa-google-plus"></i></a>
            </li>
            <li>
                <a href="https://pinterest.com"><i class="fa fa-pinterest"></i></a>
            </li>
            <li>
                <a href="https://linkedin.com"><i class="fa fa-linkedin"></i></a>
            </li>
        </ul>
    </div>
    <div class="languages top">
        <?php
        $home = str_replace('index','',$this->serverUrl());
        $fiUrl = $home . '/fi';
        $enUrl = $home . '/en';
        $cnUrl = $home . '/cn';
//        $enUrl = str_replace('cn','en',$home);
//        $cnUrl = str_replace('en','cn',$home);
        if (strpos($fiUrl,'fi') === false) {
            $fiUrl = $fiUrl."/fi";
        }
        if (strpos($enUrl,'en') === false) {
            $enUrl = $enUrl."/en";
        }
        if (strpos($cnUrl,'cn') === false) {
            $cnUrl = $cnUrl."/cn";
        }
        ?>
        <ul>
            <li>
                <a  onclick="location.href='<?php echo $fiUrl; ?>'"  title="Suomi"><span>FI</span></a>
            </li>
            <li>
                <a  onclick="location.href='<?php echo $enUrl; ?>'"  title="English"><span>EN</span></a>
            </li>
            <li>
                <a  onclick="location.href='<?php echo $cnUrl; ?>'"  title="中文"><span>CN</span></a>
            </li>
        </ul>
    </div>
    <div class="arrow-nav hidden-sm hidden-md hidden-lg">
        <a href="restaurant">
            <i class="fa fa-share"></i>
        </a>
    </div>
    <div id="maximage">
        <div>
            <img src="http://placehold.it/2560x1440" alt="" class="current-slide" data-href=".slide1"/>
        </div>
        <div>
            <img src="http://placehold.it/2560x1440" alt="" data-href=".slide2"/>
        </div>
        <div>
            <img src="http://placehold.it/2560x1440" alt="" data-href=".slide3"/>
        </div>
        <div>
            <img src="http://placehold.it/2560x1440" alt="" data-href=".slide3"/>
        </div>
        <div>
            <img src="http://placehold.it/2560x1440" alt="" data-href=".slide3"/>
        </div>
    </div>
</div>