<div class="dynamic-content restaurant-wrapper" id="main-content">
    <div class="container">
        <div id="restaurant" class="padding-wrapper">
            <div class="row">
                <div class="col-md-6">
                    <div class="square square-big gallery">
                        <i class="fa fa-pencil-square-o "></i>
                            <div class="square-bg"></div>
                            <div class="square-header">
                                <p class="title">Gallery</p>
                                <p class="description">Chinese <strong>Cusine</strong></p>
                            </div>
                            <div class="square-post">
                                <p class="title">Lorem ipsum dolor sit amet</p>
                                <p class="description">Lorem ipsum dolor sit amet, consectetur Lorem ipsum dolor sit ametadipiscing elit. Integer sapien odio, consectetur ac porta vitae, fringilla at justo. Nulla id nisl turpis. Quisque rutrum, sem a auctor feugiat, justo purus euismod ligula, quis mollis diam ligula in justo... </p>
                            </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="square reservation">
                                <i class="fa fa-calendar-o"></i>
                                <a href="reservation">
                                    <div class="square-bg" ></div>
                                    <div class="square-header">
                                        <p class="title">Reserve</p>
                                        <p class="description">your <strong>table</strong></p>
                                    </div>
                                    <div class="square-post">
                                        <p class="title">Go to <strong>reservation <i class="fa fa-arrow-circle-o-right"></i></strong></p>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="square contact">
                                <i class="fa fa-globe "></i>
                                <a href="contact">
                                    <div class="square-bg" ></div>
                                    <div class="square-header">
                                        <p class="title">Contact</p>
                                        <p class="description">with <strong>us</strong></p>
                                    </div>
                                    <div class="square-post">
                                        <p class="title">Go to<br/> <strong>contact <i class="fa fa-arrow-circle-o-right"></i></strong></p>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="controls"></div>
                            <div class="square menu-slider">
                                <div id="carousel-menu" class="carousel-menu owl-carousel owl-theme">
                                    <div class="item square-item slider1">
                                        <div class="square-bg"></div>
                                        <div class="square-header">
                                            <p class="title">Burbon Chicken</p>
                                            <p class="description">two for one until <strong>sunday</strong></p>
                                        </div>
                                    </div>
                                    <div class="item square-item slider2">
                                        <div class="square-bg"></div>
                                        <div class="square-header">
                                            <p class="title">Crock Pot Chicken</p>
                                            <p class="description">two for one until <strong>sunday</strong></p>
                                        </div>
                                    </div>
                                    <div class="item square-item slider3">
                                        <div class="square-bg"></div>
                                        <div class="square-header">
                                            <p class="title">To Die for Crock Pot Roast</p>
                                            <p class="description">two for one until <strong>sunday</strong></p>
                                        </div>
                                    </div>
                                </div>
                                <a href="menu">
                                    <div class="square-post">
                                        <p class="title">Go to <br/><strong>menu <i class="fa fa-arrow-circle-o-right"></i></strong></p>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="square opening-hour">
                                <div class="square-bg"></div>
                                <i class="fa fa-clock-o"></i>
                                <div class="square-header">
                                    <p class="title">Friday</p>
                                    <p class="description">we are <strong>open</strong></p>
                                </div>
                                <div class="square-post">
                                    <ul class="days">
                                        <li><span>Mo.</span> <strong>closed</strong></li>
                                        <li><span>Tu.</span> <strong>1:00pm - 11:00pm</strong></li>
                                        <li><span>We.</span> <strong>1:00pm - 11:00pm</strong></li>
                                        <li><span>Th.</span> <strong>1:00pm - 11:00pm</strong></li>
                                        <li><span>Fr.</span> <strong>2:00pm - 1:00am</strong></li>
                                        <li><span>Sa.</span> <strong>2:00pm - 1:00am</strong></li>
                                        <li><span>Su.</span> <strong>1:00pm - 11:00pm</strong></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="square special-offer">
                                <i class="fa fa-group "></i>
                                <a href="team">
                                    <div class="square-bg"></div>
                                    <div class="square-header">
                                        <p class="title">Our</p>
                                        <p class="description">special <strong>offers</strong></p>
                                    </div>
                                    <div class="square-post">
                                        <p class="title">Go to<br/> <strong>team <i class="fa fa-arrow-circle-o-right"></i></strong></p>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="col-md-12">
                            <div class="square lunch-buffet">
                                <i class="fa fa-group "></i>
                                <div class="square-bg"></div>
                                <div class="square-header">
                                    <p class="title">Lorem ipsum </p>
                                    <p class="description">dolor sit amet, <strong>consectetur</strong></p>
                                </div>
                                <div class="square-post">
                                    <p class="title">Go to<br/> <strong>other <i class="fa fa-arrow-circle-o-right"></i></strong></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
