<div class="dynamic-content container " id="main-content">
    <div id="team" class="padding-wrapper">
        <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-3 team">
                <div class="photo-person">
                    <figure>
                        <img class="base-photo" src="http://placehold.it/300x220" alt=""/>
                        <img class="color-photo" src="http://placehold.it/300x220/000000" alt=""/>
                    </figure>
                </div>
                <div class="name">
                    <strong>Mike Tyson</strong>
                    <span>ceo/chef</span>
                </div>
                <div class="description">
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ultricies vel felis in commodo. Donec dapibus risus purus, ac dignissim ligula lacinia et. Maecenas sit amet vehicula est. Vestibulum dictum, dui sed pulvinar elementum, risus nibh dignissim justo, at porttitor leo lorem a lectus. </p>
                </div>
                <div class="social-media">
                    <ul>
                        <li>
                            <a href="#"><i class="fa fa-linkedin"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-3 team">
                <div class="photo-person">
                    <figure>
                        <img class="base-photo" src="http://placehold.it/300x220" alt=""/>
                        <img class="color-photo" src="http://placehold.it/300x220/000000" alt=""/>
                    </figure>
                </div>
                <div class="name">
                    <strong>Josh Taylor</strong>
                    <span>chef</span>
                </div>
                <div class="description">
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ultricies vel felis in commodo. Donec dapibus risus purus, ac dignissim ligula lacinia et. Maecenas sit amet vehicula est. Vestibulum dictum, dui sed pulvinar elementum, risus nibh dignissim justo, at porttitor leo lorem a lectus. </p>
                </div>
                <div class="social-media">
                    <ul>
                        <li>
                            <a href="#"><i class="fa fa-linkedin"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-3 team">
                <div class="photo-person">
                    <figure>
                        <img class="base-photo" src="http://placehold.it/300x220" alt=""/>
                        <img class="color-photo" src="http://placehold.it/300x220/000000" alt=""/>
                    </figure>
                </div>
                <div class="name">
                    <strong>John Dobrovolsky</strong>
                    <span>business manager</span>
                </div>
                <div class="description">
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ultricies vel felis in commodo. Donec dapibus risus purus, ac dignissim ligula lacinia et. Maecenas sit amet vehicula est. Vestibulum dictum, dui sed pulvinar elementum, risus nibh dignissim justo, at porttitor leo lorem a lectus. </p>
                </div>
                <div class="social-media">
                    <ul>
                        <li>
                            <a href="#"><i class="fa fa-linkedin"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-3 team">
                <div class="photo-person">
                    <figure>
                        <img class="base-photo" src="http://placehold.it/300x220" alt=""/>
                        <img class="color-photo" src="http://placehold.it/300x220/000000" alt=""/>
                    </figure>
                </div>
                <div class="name">
                    <strong>Sasha Tyson</strong>
                    <span>waitress</span>
                </div>
                <div class="description">
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ultricies vel felis in commodo. Donec dapibus risus purus, ac dignissim ligula lacinia et. Maecenas sit amet vehicula est. Vestibulum dictum, dui sed pulvinar elementum, risus nibh dignissim justo, at porttitor leo lorem a lectus. </p>
                </div>
                <div class="social-media">
                    <ul>
                        <li>
                            <a href="#"><i class="fa fa-linkedin"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>