<?php
$title = 'Add new dish';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('menu', array('action' => 'add')));
$form->prepare();
?>
<?php echo $this->form()->openTag($form) . PHP_EOL; ?>
<form role="form">
    <div class="form-group">
        <?php echo $this->formRow($form->get('fName')) . PHP_EOL; ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('cName')) . PHP_EOL; ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('eName')) . PHP_EOL; ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('description')) . PHP_EOL; ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('spiceDgree')) . PHP_EOL; ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('price')) . PHP_EOL; ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('image')) . PHP_EOL; ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('category')) . PHP_EOL; ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('restaurant')) . PHP_EOL; ?>
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
</form>
<?php echo $this->form()->closeTag($form) . PHP_EOL; ?>